In [ ]:
import pandas as pd
import numpy as np

In [4]:
x1=np.array([4,5,6,7])
x2=np.array([1,2,3,4,5,6])

In [6]:
np.intersect1d(x1,x2) #intersection of elements of x1 and x2, returns in properly sorted format

array([4, 5, 6])

In [7]:
np.union1d(x1,x2) #union of elements, returns in sorted format 

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
np.setdiff1d(x1,x2) #elements exclusive to x1, not present  in x2

array([7])

In [ ]:
np.setxorld(x1,x2) #union of unique elements

In [11]:
x3=np.array([4,10,2,5])

In [12]:
np.in1d(x1,x3)

array([ True,  True, False, False])

In [13]:
np.where(np.in1d(x1,x3))

(array([0, 1], dtype=int64),)

In [15]:
a1=np.array([[1,4,7],[3,5,8]])

In [17]:
a2=np.array([[2,3,4],[6,5,3],[8,1,2]])
a1.dot(a2) #multiplication of a1 and a2

array([[ 82,  30,  30],
       [100,  42,  43]])

In [18]:
np.matmul(a1,a2)

array([[ 82,  30,  30],
       [100,  42,  43]])

In [20]:
a2

array([[2, 3, 4],
       [6, 5, 3],
       [8, 1, 2]])

In [23]:
from numpy.linalg import inv

In [26]:
#determinant will always be a square matrics
a3=np.array([[1,2,3],[4,5,2],[6,8,7]])

np.linalg.det(a3)

-7.000000000000001

In [ ]:
mp.linalg.inv(3)

In [45]:
a1.dot(a3)

array([[59, 78, 60],
       [71, 95, 75]])

In [27]:
from numpy import random

In [28]:
np.random.rand(10) #takes 10 random values

array([0.00930648, 0.82639917, 0.64724355, 0.53561738, 0.3018223 ,
       0.42066334, 0.89850295, 0.89716804, 0.62293568, 0.63194592])

In [29]:
np.round(np.random.rand(10),3) #rounds the random value till three digits

array([0.386, 0.735, 0.353, 0.303, 0.558, 0.16 , 0.77 , 0.67 , 0.051,
       0.5  ])

In [30]:
np.random.randint(20,50) #random integer betn 20 -50

23

In [32]:
np.random.randint(20,50,10) #random integer betn 20-50 provides 10 as unit

array([36, 20, 23, 42, 24, 47, 24, 37, 42, 39])

In [42]:
#num betn 10 and 50 and three places of decimal
np.round(np.random.rand(10),3)+np.random.randint(10,50,10)

array([36.746, 41.658, 27.012, 30.371, 17.413, 48.513, 20.694, 21.69 ,
       11.063, 17.758])

In [ ]:
#vstack adds new row array increases vertically
#hstack adds new column increases horizontally