In [51]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
import os
os.getcwd()
os.chdir(r"C:\Users\athar\Downloads")
import scipy
from scipy import stats

import numpy as np
from numpy import random
import pandas as pd
import scipy
from scipy import stats

import matplotlib
from matplotlib import pyplot as plt
import seaborn as sns
import pylab
from pylab import legend #heading, referred as label/scale
from pylab import plot, show, title, xlabel, ylabel 

import scipy
from scipy import stats
from scipy.stats import binom,poisson
from scipy.stats import expon
from scipy.stats import norm,t
from scipy.stats import rv_discrete
from scipy.stats import *
import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from scipy.stats import chi2
from statsmodels.stats import proportion 
from statsmodels.stats.proportion import proportions_ztest 
from statsmodels.stats import proportion as ssp 
from scipy.stats import chisquare
from scipy.stats import chi2_contingency 
from statsmodels.stats import rates 
from statsmodels.stats.rates import test_poisson
from statsmodels.stats.rates import test_poisson_2indep 

In [30]:
"""
H0 prop(M)-prop(p)>=12
Ha prop(M)-prop(p)<12
CL=0.95
LoS=0.05"""

'\nH0 prop(M)-prop(p)>=12\nHa prop(M)-prop(p)<12\nCL=0.95\nLoS=0.05'

# two sample proportion 

In [2]:

H0 prop(M)-prop(p)>=12
Ha prop(M)-prop(p)<12
CL=0.95
LoS=0.05

SyntaxError: invalid decimal literal (333244178.py, line 4)

In [6]:
engg=np.array([45,60])
counts=np.array([70,100])

In [7]:
ssp.proportions_ztest(engg,counts,value=0.12,alternative='smaller')

(-1.018633307307723, 0.15418854277526844)

In [9]:
45/70-60/100

0.04285714285714293

In [ ]:
#Chi-square test for goodness of fit. 
"""
When there is a single categorical variable, this test is used. Obviously, with multiple categories. Categorical variable ek ho ka, but it can have 
multiple levels.Like, for example, "model of the car" is one variable. Levels could be Maruti, Hyundai, Kata, Mercedes, Volkswagen. So, this test is
used when there
is one categorical variable. The counts obtained from a sample (the counts for different levels or categories) need to be compared against the claimed
pattern. And establish whether the difference is statistically significant or not. 
The null hypothesis for these state is: the count follows the pattern. 
"""

In [ ]:
"""
Model of Car  pattern   counts
Maruti        0.35      120
TATA          0.3       105
Hyundai       0.15      80
Toyota        0.12      50
Mercedes      0.08      30
"""

In [11]:
pattern=np.array([0.35,0.3,0.15,0.12,0.08])
obs_counts=np.array([120,105,80,50,30])

In [12]:
sum(obs_counts) 

385

In [20]:
exp_counts=pattern*sum(obs_counts) 
exp_counts
#Formula for Expected Count 

array([134.75, 115.5 ,  57.75,  46.2 ,  30.8 ])

In [16]:
scipy.stats.chisquare(obs_counts,f_exp=exp_counts)

Power_divergenceResult(statistic=11.474953617810764, pvalue=0.021714146578774157)

In [18]:
ts_array=(obs_counts-exp_counts)**2/(exp_counts)
ts_array

array([1.61456401, 0.95454545, 8.57251082, 0.31255411, 0.02077922])

In [19]:
np.sum(ts_array) #11.474953617810764
#This value is same as the test statistic. 

11.474953617810764

In [ ]:
#Category which made the most significant contribution is the one with the 8.572 value. In this case, that is Hyundai.
"""
Means that expected count for Hyundai is 50, but the observed count is 80. So, there is a significant difference.
 And we can observe one more thing in ts_array, the value in the last index is 0.020 which is smallest. It refers that there is very small difference between the observed and expected count of Mercedes. 
 You can see that the observed count is 30 and the expected count is 30.8. 
"""

# Chi-Square Test for Degree of Association. 


In [ ]:
"""Degree of association is used when you have two categorical variables. Number of variables for each. 
The number of vaiables for each categorical variable may not be the same. 
This test is used to check whether the choice made from the levels of one variable depends on the level of the second variable. ""'

In [ ]:
"""Null hypothesis The two variables Are not associated with each other.
        veg     Nonveg    Fastfood
male    110     150       40
female  120     80        90

"""

In [34]:
data=np.array([[110,150,40],[120,80,90]])

In [35]:
chi2_contingency(data)
"""
(Number of rows - 1) * (number of columns - 1) = degree of freedom. 

 expected_freq=array([[116.94915254, 116.94915254,  66.10169492],
       [113.05084746, 113.05084746,  63.89830508]]))
 if the choice of food was not associated with the gender, these are supposed to be the expected values. As we reject the null hypothesis,
 the food choice is dependent upon the gender. 

"""

Chi2ContingencyResult(statistic=40.81213239534079, pvalue=1.373276704527791e-09, dof=2, expected_freq=array([[116.94915254, 116.94915254,  66.10169492],
       [113.05084746, 113.05084746,  63.89830508]]))

In [ ]:
"""
The expected frequency is counted in the following way: manual calculation. 
for specific values like fastfood expected count of females
female(fast food)=total fast food* total female/total count

"""

In [42]:
exp_values=chi2_contingency(data)[3]
ts=(exp_values-data)**2/exp_values
ts

array([[ 0.41292066,  9.34045689, 10.30682312],
       [ 0.4271593 ,  9.66254161, 10.66223081]])

In [41]:
sum(sum(ts))

40.81213239534079

# One-sample Poisson rate

In [ ]:
"""The rate of the event in a sample when the rate of the event occurring in a sample.
I will show you how to do it in this data. This tool is used to compare the rate at which different events occur in a sample against the value. 
This test is used to compare the rate at which an event occurs in the sample against a claim value and establish whether the difference is 
statistically significant. """

In [ ]:
#No Accidents are limited to 12 per day. 
"""
H0 n<=12, Ha>12
In sample of 10 days, there were 135 accidents. Does, this data justifies the claim. 
"""

In [46]:
test_poisson(135,10,12,method='score',alternative='larger')
"""
The syntax for input is:
1. Total number of events
2. Total number of days
3. number of events expected 
4.method of score (by default)
5. Alternative
"""

<class 'statsmodels.stats.base.HolderTuple'>
statistic = 1.3693063937629153
pvalue = 0.08545176011539873
distribution = 'normal'
method = 'score'
alternative = 'larger'
rate = 13.5
nobs = 10
tuple = (1.3693063937629153, 0.08545176011539873)

# Two sample Poisson test
Difference of the rates of an event occurring in two different samples is compared against a claim value and establishes the statistical significance or not. 

In [ ]:
# H0: Rate of Mumbai - rate of Bangalore ≥ 4 
# Ha: rate of Mumbai - rate of Bangalore < 4. 

In [ ]:
"""
135 accidents reported in 10 days in Mumbai. 
140 accidents reported in 15 days in Bangalore. 
"""

In [49]:
test_poisson_2indep(135,10,130,15,value=4,compare='diff',method='score',alternative='smaller')

<class 'statsmodels.stats.base.HolderTuple'>
statistic = 0.6064446508174207
pvalue = 0.7278902369856597
distribution = 'normal'
compare = 'diff'
method = 'score'
alternative = 'smaller'
rates = (13.5, 8.666666666666666)
ratio = 1.5576923076923077
diff = 4.833333333333334
value = 4
rates_cmle = (12.929387178015027, 8.929387178015027)
ratio_null = None
tuple = (0.6064446508174207, 0.7278902369856597)

In [ ]:
#Application of PAIRED T-Test in Mumbai local. 

In [53]:
df=pd.read_excel('CDAC_DataBook.xlsx',sheet_name='faithful')

In [54]:
erupt=df.eruptions

In [55]:
np.var(erupt,ddof=1)

1.3027283328494672

In [56]:
scipy.stats.chi2.ppf(0.025,len(erupt)-1)

227.29308712885378

In [57]:
scipy.stats.chi2.ppf(0.975,len(erupt)-1)

318.49350899351583

In [61]:
1.3027283328494672*(len(erupt)-1)/318.49350899351583

1.1084664780700229

In [62]:
1.3027283328494672*(len(erupt)-1)/227.29308712885378

1.55323412014755

In [ ]:
1)One-sample t test
 
2) two-sample t-test 
revenue from two various train class. 
3) PAIRED T Test 
the speed of train before the maintenance of the track and after the maintenance of the track (-of-the-same-local). 
4)One-way ANOVA. 
The mean time for booking a ticket against the different modes like counter ,UTS or machine. 
5)Two way ANOVA
 interaction between the train line, the mode of booking the ticket, and the revenue of the people on that line. 
6) one-sample variance test 

7) two-sample variance test 

8) one-sample proportion test. 
Nearly 80% of the people travel with tickets. 
Number of delays 
Atleat 70% of people traveling in second class are men. 
9)Two Sample Proportion Test 

10)

11)

In [ ]:

The difference between Pune local and Mumbai local is not more than two minutes.
Average of Pune minus average of Mumbai is less than or equal to 2.    
It's a right-tailed test. 


When you are at a junction like Pune  or it could be a normal station like Phaazhud, 
the difference in the waiting time for the local may or may not be there. I am not saying it is there or 
it is not there; that is the difference between the waiting time at a junction 
and waiting time at a normal station. This is just a hint that I give you now; try to 

Travel time in peak hours versus travel time in non-peak hours. 


Efficiency of Local before Upgradation and after Upgradation 