In [2]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")


In [66]:
x1=[4,5,6]
type(x1)

list

In [67]:
a1=np.array(x1)
type(a1)

numpy.ndarray

In [68]:
a1=np.append(a1,2) #appends add at last

In [69]:
a1

array([4, 5, 6, 2])

In [70]:
a2=np.array([2,4,8,9])
a2

array([2, 4, 8, 9])

In [71]:
a1=np.concatenate((a1,a2))  #joins the array a1 with a2
a1

array([4, 5, 6, 2, 2, 4, 8, 9])

In [72]:
a1=np.insert(a1,3,10) #inserting at specific index, (in which array,what index, which element)

In [76]:
a1=np.insert(a1,6,np.array([7,6,4]) #adding array inside array, giving the position where to add array


SyntaxError: incomplete input (3119829159.py, line 1)

In [77]:
a1=np.delete(a1,6) #deletes the value at specific index


In [78]:
a1=np.arange(10) #take value from range 0-9

In [79]:
a1=np.arange(1,11) #from 1-10 , we use this to take value from 1-10

In [80]:
a1=np.arange(1,25,3) #jumps with the last value

In [81]:
a1

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [20]:
a1=np.arange(40,7,-3)
a1

array([40, 37, 34, 31, 28, 25, 22, 19, 16, 13, 10])

In [22]:
x2=list(a1)


[40, 37, 34, 31, 28, 25, 22, 19, 16, 13, 10]

In [ ]:
#array can be multi-dimentional

In [23]:
a1=np.array([2,4,6,3,6,5,4,3,6,7,3,5])
len(a1)

12

In [25]:
a2=a1.reshape(3,4) #can be used to create any dimentional array from eariler array
#creates a 2D array from the given array,in this case creates 2D
# check no of square brackets in start,it will tell how much D array it is
a2

array([[2, 4, 6, 3],
       [6, 5, 4, 3],
       [6, 7, 3, 5]])

In [26]:
a3=a1.reshape(3,2,2)  
a3
#first number give how many layers or stack will be there,then it defines R*C

array([[[2, 4],
        [6, 3]],

       [[6, 5],
        [4, 3]],

       [[6, 7],
        [3, 5]]])

In [4]:
k1=[3,5,6,7]
k2=[1,3,6,2]
k3=[7,4,1,6]

In [5]:
a1=np.array([k1,k2,k3])

In [29]:
a1

array([[3, 5, 6, 7],
       [1, 3, 6, 2],
       [7, 4, 1, 6]])

In [31]:
a1[2] #row with the index 2 will be extracted
a1[[0,3]]
a1[[1,2]] #extract multiple rows ie from 1-2

array([[1, 3, 6, 2],
       [7, 4, 1, 6]])

In [ ]:
a1[:,1] #extract the column with index 1 here also the format is R*C
a[:,[1,2]] #extracts multiple column out of it


In [36]:
b1=a1.reshape(-1,1) #converts any R*C into another, here -1 is used as we didnt knew the exact no of rows, and as we want only 1 column 
#we used 1 over there
b1

array([[3],
       [5],
       [6],
       [7],
       [1],
       [3],
       [6],
       [2],
       [7],
       [4],
       [1],
       [6]])

In [32]:
a1[2,:] #it returns the row with second index

array([7, 4, 1, 6])

In [ ]:
a1.flatten(order='c') #here it is converting higher dimentional array to lower,ie 2-->1 and and takes value of one row after another
a1.flatten(order='f') #here it extracts one column after another

In [83]:
a1.transpose() #converting rows into colns,or vice versa

array([[3, 1, 7],
       [5, 3, 4],
       [6, 6, 1],
       [7, 2, 6]])

In [65]:
newrow=np.array([3,6,4,2])
a1=np.vstack([a1,newrow]) #adds new row at the last position
a1
a1= a1[:-1, :]

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 11 and the array at index 1 has size 4

In [84]:
newcol=np.array([14,12,19,11])
newcol=newcol.reshape(-1,1) #we did this to convert the above array into column format
a1=np.hstack([a1,newcol])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 4

In [47]:
a1

array([[3, 5, 6, 7],
       [1, 3, 6, 2],
       [7, 4, 1, 6],
       [3, 6, 4, 2]])

In [62]:
a1=np.insert(a1,2,[3,5,7,6,9],axis=0) # axis=0 means frame of reference is the row,axis=1 means it column
#overall syntax insert(which array,index of row/coln,[elements to add],axis=0/1)

In [63]:
a1

array([1, 2, 3, 5, 7, 6, 9, 3, 4, 5, 6])

In [52]:
a1=np.insert(a1,3,[4,6,3,6,7],axis=1)

In [54]:
np.delete(a1,(0,2),axis=0)  #removes row at index 0 and 2 ,rows are removed as axis=0 
np.delete(a1,(1,3),axis=1)

array([[ 3,  6,  7, 14],
       [ 1,  6,  2, 12],
       [ 3,  7,  6,  9],
       [ 7,  1,  6, 19],
       [ 3,  4,  2, 11]])

Broadcasting in Array

In [59]:
a1=np.array([1,2,3,4,5,6])


array([1, 2, 3, 4, 5, 6])

In [55]:
a1+2 #adds 2 to every element in array

array([[ 5,  7,  8,  6,  9, 16],
       [ 3,  5,  8,  8,  4, 14],
       [ 5,  7,  9,  5,  8, 11],
       [ 9,  6,  3,  8,  8, 21],
       [ 5,  8,  6,  9,  4, 13]])

In [57]:
a2=np.array([3,4,5,6,2,7])

In [58]:
a1+a2 #adds a2 in every row vise element of a1

array([[ 6,  9, 11, 10,  9, 21],
       [ 4,  7, 11, 12,  4, 19],
       [ 6,  9, 12,  9,  8, 16],
       [10,  8,  6, 12,  8, 26],
       [ 6, 10,  9, 13,  4, 18]])

In [86]:
a2

array([2, 4, 8, 9])

In [88]:
a1=np.insert(a1,3,[2,3,5,3],axis=0)

In [3]:
a1

NameError: name 'a1' is not defined

In [90]:
a2=a2.reshape(-1,1)

In [91]:
a2

array([[2],
       [4],
       [8],
       [9]])

In [92]:
a1+a2 # now it added a2 in every column of a1

array([[ 5,  7,  8,  9],
       [ 5,  7, 10,  6],
       [15, 12,  9, 14],
       [11, 12, 14, 12]])

In [93]:
b1=np.array([2,4,5,6,2,7])

In [95]:
b1*2


array([ 4,  8, 10, 12,  4, 14])

In [96]:
c1=np.array([3,5,2])
d1=np.repeat(c1,[1,2,3]) #repeats the elements into the times written in subsequent number ,ie element from c1 first will be repeated 1 time,second 2 time ,
#third will be repeated three time

In [6]:
b1=np.array([2,4,5,6,2,7])
np.sort(b1) #sorts the array in ascending order
np.sort(b1)[::-1] #sorts in descending order
np.argsort(b1) #return the index of smallest to largest element present where in an array

array([0, 4, 1, 2, 3, 5], dtype=int64)

In [99]:
a1

array([[3, 5, 6, 7],
       [1, 3, 6, 2],
       [7, 4, 1, 6],
       [2, 3, 5, 3]])

In [101]:
np.sort(a1,axis=0) #values are sorted according to the column,cahnge will be in values of row
np.sort(a1,axis=1) #values are sorted according to the row,change will be in values of coln

array([[3, 5, 6, 7],
       [1, 2, 3, 6],
       [1, 4, 6, 7],
       [2, 3, 3, 5]])

In [7]:
np.where(b1>=4) #returns the value of indices where b1>=4
#ip to np.where command is a condition to be checked or a logical array, op of np.where is the list of indices where the condn is true

(array([1, 2, 3, 5], dtype=int64),)

In [8]:
t1=np.where(b1>=4)
len(t1) #length will be 1 as all info is in single array
len(t1[0]) #this will be the len of array present in first array of data

array([2, 4, 5, 6, 2, 7])

In [ ]:
b1[[1,2,5]] # extract certain indices and provide answer to required indices

In [12]:
b1[np.where(b1>=4)]

array([4, 5, 6, 7])

In [10]:
(b1>=4).sum() #tells where/how many times value in b1>=4

4

In [13]:
a1

array([[3, 5, 6, 7],
       [1, 3, 6, 2],
       [7, 4, 1, 6]])

In [15]:
t1=np.where(a1>=4)

In [16]:
len(t1)

2

In [18]:
len(t1[1]) #num of values greater than 4

7

In [19]:
(a1>=4).sum() #num of values greater than 4

7

In [20]:
a1[t1] #get all the values that matches the required criteria/condn

array([5, 6, 7, 6, 7, 4, 6])

In [ ]:
np.unique(b1) #only unique values will be printed from the array ,by default it sorts in increasing order

In [21]:
np.unique(b1,return_index=True) #returns where the unique value is observed first and tells its index

(array([2, 4, 5, 6, 7]), array([0, 1, 2, 3, 5], dtype=int64))

In [23]:
np.unique(b1,return_counts=True) #tells the 

(array([2, 4, 5, 6, 7]), array([2, 1, 1, 1, 1], dtype=int64))

In [25]:
np.unique(b1,return_inverse=True) #return_inverse :tells the number present in b1 what it has its index in this unique formed array,eg 2 in b1 is present
#at 0th index and 4th index

(array([2, 4, 5, 6, 7]), array([0, 1, 2, 3, 0, 4], dtype=int64))

In [26]:
b1

array([2, 4, 5, 6, 2, 7])